pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -t ./...
      - go test -v github.com/drone-demos/drone-go-selenium/task
      - cd todo
      - "go run todo.go &"
      - go test -v

compose:
  selenium:
    image: selenium/standalone-chrome
