workspace:
  base: /go
  path: src/github.com/drone-demos/drone-go-selenium

pipeline:
  test:
    image: golang:1.8
    commands:
      - cd todo
      - "go run todo.go &"
      - go test -v

services:
  selenium:
    image: selenium/standalone-chrome

