workspace:
  base: /go

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get github.com/mattn/go-sqlite3
      - go get github.com/gorilla/mux
      - go get sourcegraph.com/sourcegraph/go-selenium
      - go test -v github.com/drone-demos/drone-go-selenium/task
      - cd todo
      - "go run todo.go &"
      - go test -v

services:
  selenium:
    image: selenium/standalone-chrome
