workspace:
  base: /go
  path: src/github.com/drone-demos/drone-go-selenium

pipeline:
  test:
    image: golang:1.8
    commands:
      - cd todo
      - "go run todo.go &"
      - BROWSER=firefox go test -v
      - BROWSER=chrome go test -v

services:
  selenium:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome:2.48.2
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
  firefox:
    image: selenium/node-firefox:2.48.2
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
      DISPLAY: ":98.0"
