build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go get -t ./...
    - go test -cover -v github.com/drone-demos/drone-go-selenium/task
    - cd todo
    - "go run todo.go &"
    - go test -v

compose:
  selenium:
    image: selenium/standalone-chrome
